version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: vi-timer-be
    volumes:
      - ./backend/prisma/dev.db:/opt/app/prisma/dev.db
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vi-timer-fe
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - backend